global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'echodj'
    static_configs:
      - targets: ['echodj:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'echosplit'
    static_configs:
      - targets: ['echosplit:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'echoplay'
    static_configs:
      - targets: ['echoplay:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'echoshare'
    static_configs:
      - targets: ['echoshare:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'echostore'
    static_configs:
      - targets: ['echostore:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093